fix include errors
This fixes the following issue:

nvs.c: In function 'get_mac_addr':
nvs.c:335: error: storage size of 'ifr' isn't known
nvs.c:346: error: invalid application of 'sizeof' to incomplete type
'struct ifreq'
nvs.c:335: warning: unused variable 'ifr'

(leaving <linux/wireless.h> caused some redefinition issue,
so remove it)

Signed-off-by: Eliad Peller <eliad@wizery.com>